### ISSUE TITLE
Add support for irace v4

### ISSUE THREAD

**Issue by MLopez-Ibanez** [Saethox/iracepy-tiny#3]
Hi,

The next version of irace: https://github.com/MLopez-Ibanez/irace/tree/v4
will have some breaking changes: https://mlopez-ibanez.github.io/irace/news/index.html

I am happy to answer any questions.

**Comment by Saethox** [comment]
Looks like the most relevant changes to this wrapper are that `parameters` were moved into `scenario` and the merging of `parametersNew()`. I'll look into it.

**Comment by Saethox** [comment]
Should work with the latest commit ([#1fdbba6](https://github.com/MLopez-Ibanez/irace/tree/1fdbba610a263a5dd2372a760d33164809e8495f)) now.
